# Generated by Django 4.0.3 on 2022-03-06 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 0, 54, 9, 158302)),
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 3, 6, 0, 54, 9, 158725))),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio_dashboard.vendedor')),
            ],
        ),
    ]
